[project]
name = "learning-nano-vllm"
version = "0.1.0"
description = "my learnings of nano-vllm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.4.0",
    "triton>=3.0.0",
    "transformers>=4.51.0",
    "flash-attn",
    "xxhash",
    "pytest",
]
